export const componentCatalog = [
  [
    'Button',
    '按钮',
    'button',
    '通用',
    'General',
    '触发保存、提交等操作。',
    'Trigger actions such as saving or submitting.',
  ],
  [
    'Steps',
    '步骤条',
    'steps',
    '导航',
    'Navigation',
    '查看任务步骤与进度。',
    'Follow task steps and progress.',
  ],
  [
    'Breadcrumb',
    '面包屑',
    'breadcrumb',
    '导航',
    'Navigation',
    '展示页面所在层级。',
    'Show the page hierarchy.',
  ],
  [
    'Pagination',
    '分页',
    'pagination',
    '导航',
    'Navigation',
    '按页浏览较多数据。',
    'Browse data by page.',
  ],
  [
    'Tabs',
    '标签页',
    'tabs',
    '导航',
    'Navigation',
    '在同一区域切换内容。',
    'Switch between content views.',
  ],
  [
    'Tag',
    '标签',
    'tag',
    '数据展示',
    'Data display',
    '标记分类或状态。',
    'Label categories or statuses.',
  ],
  [
    'Badge',
    '角标',
    'badge',
    '数据展示',
    'Data display',
    '显示数量和未读提醒。',
    'Show counts and notifications.',
  ],
  [
    'Input',
    '输入框',
    'input',
    '数据录入',
    'Data entry',
    '输入单行文本。',
    'Enter a single line of text.',
  ],
  [
    'InputNumber',
    '数字输入框',
    'input-number',
    '数据录入',
    'Data entry',
    '填写数量、金额等数字。',
    'Enter quantities, prices and numbers.',
  ],
  [
    'Textarea',
    '文本域',
    'textarea',
    '数据录入',
    'Data entry',
    '填写多行内容。',
    'Enter multiple lines of text.',
  ],
  [
    'Checkbox',
    '复选框',
    'checkbox',
    '数据录入',
    'Data entry',
    '勾选一个或多个选项。',
    'Select one or more options.',
  ],
  [
    'Radio',
    '单选框',
    'radio',
    '数据录入',
    'Data entry',
    '从一组中选择一项。',
    'Choose one option from a group.',
  ],
  [
    'Switch',
    '开关',
    'switch',
    '数据录入',
    'Data entry',
    '即时开启或关闭设置。',
    'Turn a setting on or off.',
  ],
  [
    'Select',
    '选择器',
    'select',
    '数据录入',
    'Data entry',
    '从下拉列表中选择。',
    'Choose an option from a list.',
  ],
  [
    'AutoComplete',
    '自动完成',
    'auto-complete',
    '数据录入',
    'Data entry',
    '根据建议完成输入。',
    'Complete input with suggestions.',
  ],
  [
    'Cascader',
    '级联选择',
    'cascader',
    '数据录入',
    'Data entry',
    '逐级选择地区或分类。',
    'Choose a hierarchical value.',
  ],
  [
    'Form',
    '表单',
    'form',
    '数据录入',
    'Data entry',
    '组织字段与校验反馈。',
    'Organize fields and validation.',
  ],
  [
    'DatePicker',
    '日期选择器',
    'date-picker',
    '日期与时间',
    'Date and time',
    '从日历中选择日期。',
    'Choose a date from a calendar.',
  ],
  [
    'TimePicker',
    '时间选择器',
    'time-picker',
    '日期与时间',
    'Date and time',
    '选择小时、分钟和秒。',
    'Choose hours, minutes and seconds.',
  ],
  [
    'DateTimePicker',
    '日期时间选择器',
    'date-time-picker',
    '日期与时间',
    'Date and time',
    '选择具体的日期与时间。',
    'Choose a specific date and time.',
  ],
  [
    'DateRangePicker',
    '日期区间选择器',
    'date-range-picker',
    '日期与时间',
    'Date and time',
    '选择起止日期或时间。',
    'Choose a date or time range.',
  ],
  [
    'Calendar',
    '日历',
    'calendar',
    '日期与时间',
    'Date and time',
    '浏览日期与日程安排。',
    'Browse dates and schedules.',
  ],
  [
    'Dropdown',
    '下拉菜单',
    'dropdown',
    '反馈与交互',
    'Feedback',
    '在菜单中收纳操作。',
    'Group actions in a menu.',
  ],
  [
    'Modal',
    '弹窗',
    'modal',
    '反馈与交互',
    'Feedback',
    '在弹窗中查看或编辑。',
    'View or edit inside a dialog.',
  ],
  [
    'Drawer',
    '抽屉',
    'drawer',
    '反馈与交互',
    'Feedback',
    '从页面边缘展开内容。',
    'Open content from a page edge.',
  ],
  [
    'Confirm',
    '确认框',
    'confirm',
    '反馈与交互',
    'Feedback',
    '执行重要操作前确认。',
    'Confirm important actions.',
  ],
  [
    'Alert',
    '警告提示',
    'alert',
    '反馈与交互',
    'Feedback',
    '提示需关注的信息。',
    'Display information that needs attention.',
  ],
  [
    'Message',
    '消息提示',
    'message',
    '反馈与交互',
    'Feedback',
    '短暂反馈操作结果。',
    'Show brief operation feedback.',
  ],
  [
    'Loading',
    '加载',
    'loading',
    '反馈与交互',
    'Feedback',
    '提示内容正在加载。',
    'Indicate loading content.',
  ],
  [
    'Progress',
    '进度条',
    'progress',
    '反馈与交互',
    'Feedback',
    '展示任务完成程度。',
    'Display task completion.',
  ],
  [
    'Tooltip',
    '文字提示',
    'tooltip',
    '反馈与交互',
    'Feedback',
    '补充简短说明。',
    'Add brief explanations.',
  ],
  [
    'ConfigProvider',
    '配置',
    'config-provider',
    '配置',
    'Configuration',
    '按区域定制主题与语言。',
    'Set regional themes and languages.',
  ],
] as const;
