export const componentCatalog = [
  [
    'Button',
    '按钮',
    'button',
    '通用',
    'General',
    '触发保存、提交等操作。',
    'Trigger actions such as saving or submitting.',
  ],
  [
    'Steps',
    '步骤条',
    'steps',
    '导航',
    'Navigation',
    '查看任务步骤与进度。',
    'Follow task steps and progress.',
  ],
  [
    'Breadcrumb',
    '面包屑',
    'breadcrumb',
    '导航',
    'Navigation',
    '展示页面所在层级。',
    'Show the page hierarchy.',
  ],
  [
    'Pagination',
    '分页',
    'pagination',
    '导航',
    'Navigation',
    '按页浏览较多数据。',
    'Browse data by page.',
  ],
  [
    'Tabs',
    '标签页',
    'tabs',
    '导航',
    'Navigation',
    '在同一区域切换内容。',
    'Switch between content views.',
  ],
  [
    'Tag',
    '标签',
    'tag',
    '数据展示',
    'Data display',
    '标记分类或状态。',
    'Label categories or statuses.',
  ],
  [
    'Badge',
    '角标',
    'badge',
    '数据展示',
    'Data display',
    '显示数量和未读提醒。',
    'Show counts and notifications.',
  ],
  [
    'Input',
    '输入框',
    'input',
    '数据录入',
    'Data entry',
    '输入单行文本。',
    'Enter a single line of text.',
  ],
  [
    'InputNumber',
    '数字输入框',
    'input-number',
    '数据录入',
    'Data entry',
    '填写数量、金额等数字。',
    'Enter quantities, prices and numbers.',
  ],
  [
    'Textarea',
    '文本域',
    'textarea',
    '数据录入',
    'Data entry',
    '填写多行内容。',
    'Enter multiple lines of text.',
  ],
  [
    'Checkbox',
    '复选框',
    'checkbox',
    '数据录入',
    'Data entry',
    '勾选一个或多个选项。',
    'Select one or more options.',
  ],
  [
    'Radio',
    '单选框',
    'radio',
    '数据录入',
    'Data entry',
    '从一组中选择一项。',
    'Choose one option from a group.',
  ],
  [
    'Switch',
    '开关',
    'switch',
    '数据录入',
    'Data entry',
    '即时开启或关闭设置。',
    'Turn a setting on or off.',
  ],
  [
    'Select',
    '选择器',
    'select',
    '数据录入',
    'Data entry',
    '从下拉列表中选择。',
    'Choose an option from a list.',
  ],
  [
    'AutoComplete',
    '自动完成',
    'auto-complete',
    '数据录入',
    'Data entry',
    '根据建议完成输入。',
    'Complete input with suggestions.',
  ],
  [
    'Cascader',
    '级联选择',
    'cascader',
    '数据录入',
    'Data entry',
    '逐级选择地区或分类。',
    'Choose a hierarchical value.',
  ],
  [
    'Form',
    '表单',
    'form',
    '数据录入',
    'Data entry',
    '组织字段与校验反馈。',
    'Organize fields and validation.',
  ],
  [
    'DatePicker',
    '日期选择器',
    'date-picker',
    '日期与时间',
    'Date and time',
    '从日历中选择日期。',
    'Choose a date from a calendar.',
  ],
  [
    'TimePicker',
    '时间选择器',
    'time-picker',
    '日期与时间',
    'Date and time',
    '选择小时、分钟和秒。',
    'Choose hours, minutes and seconds.',
  ],
  [
    'DateTimePicker',
    '日期时间选择器',
    'date-time-picker',
    '日期与时间',
    'Date and time',
    '选择具体的日期与时间。',
    'Choose a specific date and time.',
  ],
  [
    'DateRangePicker',
    '日期区间选择器',
    'date-range-picker',
    '日期与时间',
    'Date and time',
    '选择起止日期或时间。',
    'Choose a date or time range.',
  ],
  [
    'Calendar',
    '日历',
    'calendar',
    '日期与时间',
    'Date and time',
    '浏览日期与日程安排。',
    'Browse dates and schedules.',
  ],
  [
    'Dropdown',
    '下拉菜单',
    'dropdown',
    '反馈与交互',
    'Feedback',
    '在菜单中收纳操作。',
    'Group actions in a menu.',
  ],
  [
    'Modal',
    '弹窗',
    'modal',
    '反馈与交互',
    'Feedback',
    '在弹窗中查看或编辑。',
    'View or edit inside a dialog.',
  ],
  [
    'Drawer',
    '抽屉',
    'drawer',
    '反馈与交互',
    'Feedback',
    '从页面边缘展开内容。',
    'Open content from a page edge.',
  ],
  [
    'Confirm',
    '确认框',
    'confirm',
    '反馈与交互',
    'Feedback',
    '执行重要操作前确认。',
    'Confirm important actions.',
  ],
  [
    'Alert',
    '警告提示',
    'alert',
    '反馈与交互',
    'Feedback',
    '提示需关注的信息。',
    'Display information that needs attention.',
  ],
  [
    'Message',
    '消息提示',
    'message',
    '反馈与交互',
    'Feedback',
    '短暂反馈操作结果。',
    'Show brief operation feedback.',
  ],
  [
    'Loading',
    '加载',
    'loading',
    '反馈与交互',
    'Feedback',
    '提示内容正在加载。',
    'Indicate loading content.',
  ],
  [
    'Progress',
    '进度条',
    'progress',
    '反馈与交互',
    'Feedback',
    '展示任务完成程度。',
    'Display task completion.',
  ],
  [
    'Tooltip',
    '文字提示',
    'tooltip',
    '反馈与交互',
    'Feedback',
    '补充简短说明。',
    'Add brief explanations.',
  ],
  [
    'ConfigProvider',
    '配置',
    'config-provider',
    '配置',
    'Configuration',
    '按区域定制主题与语言。',
    'Set regional themes and languages.',
  ],
  [
    'Avatar',
    '头像',
    'avatar',
    '数据展示',
    'Data display',
    '展示用户、团队或对象的头像。',
    'Display a user, team or object avatar.',
  ],
  [
    'Card',
    '卡片',
    'card',
    '数据展示',
    'Data display',
    '在独立容器中展示相关内容和操作。',
    'Group related content and actions in a container.',
  ],
  [
    'Divider',
    '分割线',
    'divider',
    '通用',
    'General',
    '分隔内容、段落或一组操作。',
    'Separate content, paragraphs or actions.',
  ],
  [
    'Result',
    '结果',
    'result',
    '反馈与交互',
    'Feedback',
    '展示操作结果与空数据状态。',
    'Present operation results and empty content.',
  ],
  [
    'Skeleton',
    '骨架屏',
    'skeleton',
    '反馈与交互',
    'Feedback',
    '在内容加载时展示结构占位。',
    'Show a content placeholder while loading.',
  ],
  [
    'Collapse',
    '折叠面板',
    'collapse',
    '数据展示',
    'Data display',
    '展开或收起一组内容。',
    'Expand or collapse a group of sections.',
  ],
  [
    'Popover',
    '气泡卡片',
    'popover',
    '反馈与交互',
    'Feedback',
    '在元素附近展示说明或补充操作。',
    'Show details or actions next to an element.',
  ],
  [
    'Slider',
    '滑动输入条',
    'slider',
    '数据录入',
    'Data entry',
    '通过滑动选择数值或区间。',
    'Choose a number or range by sliding.',
  ],
  [
    'Rate',
    '评分',
    'rate',
    '数据录入',
    'Data entry',
    '选择或展示评分。',
    'Select or display a rating.',
  ],
  [
    'Tree',
    '树',
    'tree',
    '数据展示',
    'Data display',
    '按层级浏览与选择内容。',
    'Browse and select hierarchical content.',
  ],
  [
    'TreeSelect',
    '树选择器',
    'tree-select',
    '数据录入',
    'Data entry',
    '从层级数据中选择值。',
    'Choose values from hierarchical data.',
  ],
  [
    'ColorPicker',
    '颜色选择器',
    'color-picker',
    '数据录入',
    'Data entry',
    '选择颜色与透明度。',
    'Choose colors and opacity.',
  ],
  [
    'Layout',
    '布局',
    'layout',
    '布局',
    'Layout',
    '组织页面的头部、侧栏、内容与底部。',
    'Organize headers, sidebars, content and footers.',
  ],
  [
    'Grid',
    '栅格',
    'grid',
    '布局',
    'Layout',
    '根据屏幕宽度排列内容。',
    'Arrange content for different screen widths.',
  ],
  [
    'Space',
    '间距',
    'space',
    '布局',
    'Layout',
    '统一一组元素之间的间距。',
    'Keep consistent spacing between elements.',
  ],
  [
    'ScrollArea',
    '滚动区域',
    'scroll-area',
    '布局',
    'Layout',
    '在限定区域内浏览内容。',
    'Browse content inside a bounded scroll area.',
  ],
  [
    'Masonry',
    '瀑布流',
    'masonry',
    '布局',
    'Layout',
    '排列高度不一的卡片与图片。',
    'Arrange cards and images of varying heights.',
  ],
  [
    'Segmented',
    '分段控制器',
    'segmented',
    '导航',
    'Navigation',
    '快速切换一组相关选项。',
    'Switch between related options.',
  ],
  [
    'Menu',
    '菜单',
    'menu',
    '导航',
    'Navigation',
    '按层级组织页面导航。',
    'Organize hierarchical navigation.',
  ],
  [
    'BackTop',
    '回到顶部',
    'back-top',
    '导航',
    'Navigation',
    '快速返回页面或滚动容器顶部。',
    'Return to the top of a page or scroll container.',
  ],
  [
    'Descriptions',
    '描述列表',
    'descriptions',
    '数据展示',
    'Data display',
    '按名称和值展示对象详情。',
    'Present object details as labels and values.',
  ],
  [
    'Image',
    '图片',
    'image',
    '媒体',
    'Media',
    '展示图片并放大浏览图片组。',
    'Display images and explore galleries.',
  ],
  [
    'QRCode',
    '二维码',
    'qr-code',
    '数据展示',
    'Data display',
    '将文本和链接展示为二维码。',
    'Present text and links as QR codes.',
  ],
  [
    'Timeline',
    '时间线',
    'timeline',
    '数据展示',
    'Data display',
    '按顺序展示事件与进展。',
    'Present events and progress in sequence.',
  ],
  [
    'VirtualList',
    '虚拟列表',
    'virtual-list',
    '数据展示',
    'Data display',
    '流畅浏览大量列表内容。',
    'Browse large lists smoothly.',
  ],
  [
    'Transfer',
    '穿梭框',
    'transfer',
    '数据录入',
    'Data entry',
    '在两个列表之间选择和移动项目。',
    'Select and move items between two lists.',
  ],
  [
    'InputOTP',
    '验证码输入',
    'input-otp',
    '数据录入',
    'Data entry',
    '输入和粘贴验证码。',
    'Enter and paste verification codes.',
  ],
  [
    'TimeRangePicker',
    '时间范围',
    'time-range-picker',
    '日期与时间',
    'Date and time',
    '选择一天内的起止时间。',
    'Choose a start and end time.',
  ],
  [
    'InputMask',
    '格式输入',
    'input-mask',
    '数据录入',
    'Data entry',
    '按照指定格式填写信息。',
    'Enter information in a specified format.',
  ],
  [
    'Notification',
    '通知提醒',
    'notification',
    '反馈与交互',
    'Feedback',
    '在页面角落展示通知与后续操作。',
    'Present notifications and actions in a page corner.',
  ],
  [
    'Popconfirm',
    '气泡确认',
    'popconfirm',
    '反馈与交互',
    'Feedback',
    '在操作位置附近确认重要操作。',
    'Confirm important actions near their triggers.',
  ],
  [
    'ErrorBoundary',
    '错误边界',
    'error-boundary',
    '反馈与交互',
    'Feedback',
    '展示内容异常时的备用界面。',
    'Provide a fallback when content fails to render.',
  ],
  [
    'LoadingBar',
    '顶部加载条',
    'loading-bar',
    '反馈与交互',
    'Feedback',
    '展示页面或任务的加载进度。',
    'Show page or task loading progress.',
  ],
  [
    'InfiniteScroll',
    '无限滚动',
    'infinite-scroll',
    '数据展示',
    'Data display',
    '浏览到列表末尾时加载更多内容。',
    'Load more content when reaching the end of a list.',
  ],
  [
    'Sortable',
    '拖拽排序',
    'sortable',
    '数据录入',
    'Data entry',
    '通过拖动或键盘调整项目顺序。',
    'Reorder items with dragging or the keyboard.',
  ],
  [
    'FilePreview',
    '文件预览',
    'file-preview',
    '媒体',
    'Media',
    '预览图片、PDF、音视频与文本文件。',
    'Preview images, PDFs, audio, video and text files.',
  ],
  [
    'ImageCropper',
    '图片裁剪',
    'image-cropper',
    '媒体',
    'Media',
    '调整图片位置、缩放与裁剪范围。',
    'Position, zoom and crop images.',
  ],
  [
    'SignaturePad',
    '签名板',
    'signature-pad',
    '媒体',
    'Media',
    '手写签名并导出图片。',
    'Capture handwritten signatures and export images.',
  ],
  [
    'OrgChart',
    '组织结构图',
    'org-chart',
    '数据展示',
    'Data display',
    '展示组织与成员之间的层级。',
    'Display hierarchies between teams and members.',
  ],
] as const;
