import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parse } from '@babel/parser';
import * as OpenCC from 'opencc-js';

// Build-time conversion keeps the locale small and avoids a runtime dictionary dependency.
const root = resolve(import.meta.dirname, '../src');
const convert = OpenCC.Converter({ from: 'cn', to: 'twp' });
const source = await readFile(resolve(root, 'config-provider/context.ts'), 'utf8');
const literal = source.match(/const zh = (\{[\s\S]*?\n\});/u)?.[1];
if (!literal) throw new Error('Chinese message source not found');
const messages = Function(`return (${literal})`)();
const traditional = Object.fromEntries(
  Object.entries(messages).map(([key, value]) => [
    key,
    Array.isArray(value) ? value.map(convert) : convert(value),
  ]),
);
const texts = {};
async function walk(directory) {
  for (const file of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, file.name);
    if (file.isDirectory() && file.name !== 'locales') await walk(path);
    else if (/\.tsx?$/u.test(file.name) && !file.name.includes('.test.')) {
      const tree = parse(await readFile(path, 'utf8'), {
        sourceType: 'module',
        plugins: ['typescript', 'jsx'],
      });
      const visit = (node) => {
        if (!node || typeof node !== 'object') return;
        if (
          node.type === 'CallExpression' &&
          node.callee?.name === 't' &&
          node.arguments.length === 2 &&
          node.arguments.every((item) => item.type === 'StringLiteral')
        ) {
          texts[node.arguments[1].value] = convert(node.arguments[0].value);
        }
        for (const value of Object.values(node))
          if (Array.isArray(value)) value.forEach(visit);
          else if (value && typeof value === 'object') visit(value);
      };
      visit(tree);
    }
  }
}
await walk(root);
await mkdir(resolve(root, 'locales'), { recursive: true });
await writeFile(
  resolve(root, 'locales/zh-tw.ts'),
  `// Generated by scripts/generate-locale.mjs using OpenCC (MIT).\nexport const traditionalMessages = ${JSON.stringify(traditional, null, 2)};\nexport const traditionalTextMessages: Record<string, string> = ${JSON.stringify(Object.fromEntries(Object.entries(texts).sort(([a], [b]) => a.localeCompare(b))), null, 2)};\n`,
);
console.log(
  `Generated zh-TW: ${Object.keys(traditional).length} messages, ${Object.keys(texts).length} component labels.`,
);
