import fs from 'node:fs';
import { build } from 'esbuild';

// Bundle the same runtime source so this command works on every supported Node LTS.
const { outputFiles } = await build({
  entryPoints: ['src/colors.ts'],
  bundle: true,
  write: false,
  platform: 'node',
  format: 'esm',
});
const { deriveColors } = await import(
  `data:text/javascript;base64,${Buffer.from(outputFiles[0].text).toString('base64')}`
);
const cssColor = (value) =>
  value.replace(
    /^rgba\((\d+), (\d+), (\d+), 1\)$/u,
    (_, r, g, b) =>
      `#${[r, g, b].map((channel) => Number(channel).toString(16).padStart(2, '0')).join('')}`,
  );
const source = ['light', 'dark']
  .map(
    (mode) =>
      `@mixin ${mode} {\n${Object.entries(deriveColors(mode))
        .map(([key, value]) => `  ${key}: ${cssColor(value)};`)
        .join('\n')}\n}`,
  )
  .join('\n\n');
const file = new URL('../src/styles/_palette.scss', import.meta.url);
const content = `// Generated by scripts/generate-palette.mjs from colors.ts and color-recipes.ts.\n${source}\n`;
if (process.argv.includes('--check')) {
  if (fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n') !== content)
    throw new Error('Static palettes are stale; run pnpm generate:palette.');
} else fs.writeFileSync(file, content);
